import type { Question } from '@/types/quiz';

/**
 * Bank Soal CNN Quiz Trainer
 * 60 soal berdasarkan materi PPT "14 - Convolution Neural Network (CNN)"
 */
export const QUESTION_BANK: Question[] = [
  // ===== CONVOLUTION — 20 SOAL =====

  // Convolution — Numeric (dot product)
  {
    id: 'conv-001',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution (dot product) dari matriks input dan kernel berikut:',
    displayData: {
      input: [[1,2,3],[4,5,6],[7,8,9]],
      kernel: [[1,0,1],[0,1,0],[1,0,1]],
    },
    answer: 25,
    explanation: 'Dot product: kalikan setiap elemen yang bersesuaian lalu jumlahkan.',
    explanationSteps: [
      '(1×1) + (2×0) + (3×1)',
      '+ (4×0) + (5×1) + (6×0)',
      '+ (7×1) + (8×0) + (9×1)',
      '= 1 + 0 + 3 + 0 + 5 + 0 + 7 + 0 + 9',
      '= 25',
    ],
  },
  {
    id: 'conv-002',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[2,1,3],[0,4,2],[1,3,5]],
      kernel: [[1,1,0],[0,1,1],[1,0,1]],
    },
    answer: 21,
    explanation: 'Kalikan elemen bersesuaian lalu jumlahkan semua hasil perkalian.',
    explanationSteps: [
      '(2×1)+(1×1)+(3×0)',
      '+(0×0)+(4×1)+(2×1)',
      '+(1×1)+(3×0)+(5×1)',
      '= 2+1+0+0+4+2+1+0+5',
      '= 15',
    ],
  },
  {
    id: 'conv-003',
    category: 'convolution',
    difficulty: 'hard',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[3,2,1],[1,0,2],[4,3,1]],
      kernel: [[0,1,0],[1,1,1],[0,1,0]],
    },
    answer: 13,
    explanation: 'Kernel ini adalah filter "cross" atau "plus" — hanya memilih elemen atas, bawah, kiri, kanan, dan tengah.',
    explanationSteps: [
      '(3×0)+(2×1)+(1×0)',
      '+(1×1)+(0×1)+(2×1)',
      '+(4×0)+(3×1)+(1×0)',
      '= 0+2+0+1+0+2+0+3+0',
      '= 8',
    ],
  },
  {
    id: 'conv-004',
    category: 'convolution',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa yang dilakukan operasi convolution pada CNN?',
    options: [
      { key: 'A', text: 'Menjumlahkan semua nilai piksel dalam gambar' },
      { key: 'B', text: 'Mengalikan setiap elemen input dengan elemen kernel yang bersesuaian, kemudian menjumlahkan hasilnya (dot product)' },
      { key: 'C', text: 'Memilih nilai maksimum dari setiap region' },
      { key: 'D', text: 'Mengubah gambar menjadi array satu dimensi' },
    ],
    answer: 'B',
    keywords: ['dot product', 'perkalian elemen', 'jumlah'],
    explanation: 'Convolution adalah operasi dot product: setiap elemen input dikalikan dengan elemen kernel yang bersesuaian, kemudian semua hasil perkalian dijumlahkan untuk menghasilkan satu nilai pada feature map.',
    explanationSteps: ['output = Σ (input[i][j] × kernel[i][j])'],
  },
  {
    id: 'conv-005',
    category: 'convolution',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa nama elemen kecil berisi bobot yang digeser di atas gambar untuk menghasilkan feature map?',
    options: [
      { key: 'A', text: 'Neuron' },
      { key: 'B', text: 'Pooling window' },
      { key: 'C', text: 'Kernel / Filter' },
      { key: 'D', text: 'Softmax layer' },
    ],
    answer: 'C',
    keywords: ['kernel', 'filter'],
    explanation: 'Kernel (juga disebut filter) adalah matriks kecil berisi bobot yang digeser di seluruh input untuk mengekstrak fitur.',
  },
  {
    id: 'conv-006',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[5,3,2],[1,4,6],[3,2,4]],
      kernel: [[1,0,0],[0,1,0],[0,0,1]],
    },
    answer: 13,
    explanation: 'Kernel diagonal identitas: hanya elemen diagonal yang dikalikan dengan 1, sisanya 0.',
    explanationSteps: [
      '(5×1)+(3×0)+(2×0)',
      '+(1×0)+(4×1)+(6×0)',
      '+(3×0)+(2×0)+(4×1)',
      '= 5+0+0+0+4+0+0+0+4',
      '= 13',
    ],
  },
  {
    id: 'conv-007',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[0,1,2],[3,4,5],[6,7,8]],
      kernel: [[0,0,1],[0,1,0],[1,0,0]],
    },
    answer: 18,
    explanation: 'Kernel anti-diagonal: mengambil elemen dari pojok kanan atas, tengah, dan pojok kiri bawah.',
    explanationSteps: [
      '(0×0)+(1×0)+(2×1)',
      '+(3×0)+(4×1)+(5×0)',
      '+(6×1)+(7×0)+(8×0)',
      '= 0+0+2+0+4+0+6+0+0',
      '= 12',
    ],
  },
  {
    id: 'conv-008',
    category: 'convolution',
    difficulty: 'hard',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[4,2,7],[1,6,3],[5,8,2]],
      kernel: [[1,2,1],[2,4,2],[1,2,1]],
    },
    answer: 96,
    explanation: 'Kernel Gaussian sederhana: elemen yang lebih dekat ke tengah memiliki bobot lebih besar.',
    explanationSteps: [
      '(4×1)+(2×2)+(7×1)',
      '+(1×2)+(6×4)+(3×2)',
      '+(5×1)+(8×2)+(2×1)',
      '= 4+4+7+2+24+6+5+16+2',
      '= 70',
    ],
  },
  {
    id: 'conv-009',
    category: 'convolution',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Mengapa CNN menggunakan kernel/filter daripada langsung menghubungkan semua piksel ke neuron?',
    options: [
      { key: 'A', text: 'Karena gambar tidak memiliki cukup piksel untuk dihubungkan langsung' },
      { key: 'B', text: 'Karena menghubungkan semua piksel langsung ke neural network membutuhkan terlalu banyak parameter (komputasi sangat besar)' },
      { key: 'C', text: 'Karena kernel dapat mengubah warna gambar dengan lebih baik' },
      { key: 'D', text: 'Karena pooling tidak bisa digunakan tanpa kernel' },
    ],
    answer: 'B',
    keywords: ['parameter', 'komputasi', 'flatten', 'pixel'],
    explanation: 'Gambar berukuran 224×224 memiliki 50.176 piksel. Jika setiap piksel dihubungkan ke satu hidden layer dengan 1000 neuron, dibutuhkan 50 juta+ parameter hanya untuk satu layer. CNN menggunakan parameter sharing melalui kernel sehingga jauh lebih efisien.',
  },
  {
    id: 'conv-010',
    category: 'convolution',
    difficulty: 'hard',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[1,3,2,5],[4,6,1,3],[2,5,4,1],[3,1,6,2]],
      kernel: [[1,0,1],[0,1,0],[1,0,1]],
    },
    answer: 22,
    explanation: 'Kernel diterapkan pada submatriks kiri atas input 4×4 untuk menghasilkan nilai pertama feature map.',
    explanationSteps: [
      'Ambil submatriks [[1,3,2],[4,6,1],[2,5,4]]',
      '(1×1)+(3×0)+(2×1)',
      '+(4×0)+(6×1)+(1×0)',
      '+(2×1)+(5×0)+(4×1)',
      '= 1+0+2+0+6+0+2+0+4',
      '= 15',
    ],
  },
  {
    id: 'conv-011',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[2,4,1],[3,0,5],[1,2,3]],
      kernel: [[0,1,0],[1,0,1],[0,1,0]],
    },
    answer: 15,
    explanation: 'Kernel "plus": mengambil nilai atas, bawah, kiri, kanan dari pusat.',
    explanationSteps: [
      '(2×0)+(4×1)+(1×0)',
      '+(3×1)+(0×0)+(5×1)',
      '+(1×0)+(2×1)+(3×0)',
      '= 0+4+0+3+0+5+0+2+0',
      '= 14',
    ],
  },
  {
    id: 'conv-012',
    category: 'convolution',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Sebuah gambar 6×6 dikonvolusikan dengan kernel 3×3 (tanpa padding, stride 1). Berapa ukuran feature map yang dihasilkan?',
    options: [
      { key: 'A', text: '6×6' },
      { key: 'B', text: '4×4' },
      { key: 'C', text: '3×3' },
      { key: 'D', text: '2×2' },
    ],
    answer: 'B',
    keywords: ['4x4', '4 × 4'],
    explanation: 'Rumus: (input - kernel) + 1 = (6 - 3) + 1 = 4. Hasilnya 4×4.',
    explanationSteps: ['(6 - 3) + 1 = 4', 'Feature map = 4×4'],
  },
  {
    id: 'conv-013',
    category: 'convolution',
    difficulty: 'hard',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[7,2,3],[4,1,6],[2,5,3]],
      kernel: [[1,1,1],[1,1,1],[1,1,1]],
    },
    answer: 33,
    explanation: 'Kernel semua satu hanya menjumlahkan semua elemen dalam window.',
    explanationSteps: ['7+2+3+4+1+6+2+5+3 = 33'],
  },
  {
    id: 'conv-014',
    category: 'convolution',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa itu feature map dalam konteks CNN?',
    options: [
      { key: 'A', text: 'Peta geografis dari lokasi fitur dalam dataset' },
      { key: 'B', text: 'Hasil dari operasi convolution antara input dan kernel — matriks yang merepresentasikan fitur yang terdeteksi' },
      { key: 'C', text: 'Layer terakhir dalam CNN sebelum output' },
      { key: 'D', text: 'Daftar semua kernel yang digunakan dalam satu layer' },
    ],
    answer: 'B',
    keywords: ['hasil convolution', 'fitur terdeteksi', 'output convolution'],
    explanation: 'Feature map adalah output dari operasi convolution. Setiap nilai dalam feature map merepresentasikan seberapa kuat suatu fitur (yang didefinisikan oleh kernel) terdeteksi pada posisi tertentu dalam input.',
  },
  {
    id: 'conv-015',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[1,0,2],[3,1,4],[2,3,1]],
      kernel: [[2,0,1],[0,3,0],[1,0,2]],
    },
    answer: 22,
    explanation: 'Perhatikan elemen yang memiliki bobot besar (3 di tengah, 2 di sudut).',
    explanationSteps: [
      '(1×2)+(0×0)+(2×1)',
      '+(3×0)+(1×3)+(4×0)',
      '+(2×1)+(3×0)+(1×2)',
      '= 2+0+2+0+3+0+2+0+2',
      '= 11',
    ],
  },
  {
    id: 'conv-016',
    category: 'convolution',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Jelaskan langkah-langkah operasi convolution secara manual pada gambar grayscale dengan satu kernel. Sebutkan minimal 3 langkah.',
    answer: 'letakkan kernel pada posisi awal input, hitung dot product, geser kernel, ulangi',
    keywords: ['kernel', 'dot product', 'geser', 'stride', 'jumlahkan', 'feature map'],
    explanation: 'Langkah convolution: (1) Letakkan kernel di sudut kiri atas input. (2) Kalikan setiap elemen kernel dengan elemen input yang bersesuaian. (3) Jumlahkan semua hasil perkalian → satu nilai output. (4) Geser kernel ke kanan (stride). (5) Ulangi hingga seluruh input terpindai. (6) Hasilnya adalah feature map.',
    explanationSteps: [
      '1. Posisikan kernel di kiri atas',
      '2. Hitung dot product (Σ input×kernel)',
      '3. Hasilnya masuk ke feature map',
      '4. Geser kernel (stride = 1)',
      '5. Ulangi sampai seluruh input dipindai',
    ],
  },
  {
    id: 'conv-017',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[2,0,1],[1,3,2],[4,1,0]],
      kernel: [[1,0,1],[0,2,0],[1,0,1]],
    },
    answer: 16,
    explanation: 'Kernel dengan bobot 2 di tengah dan 1 di sudut.',
    explanationSteps: [
      '(2×1)+(0×0)+(1×1)',
      '+(1×0)+(3×2)+(2×0)',
      '+(4×1)+(1×0)+(0×1)',
      '= 2+0+1+0+6+0+4+0+0',
      '= 13',
    ],
  },
  {
    id: 'conv-018',
    category: 'convolution',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Jika sebuah gambar ukuran 8×8 dikonvolusikan dengan kernel 5×5 (tanpa padding, stride 1), berapa ukuran feature map yang dihasilkan?',
    options: [
      { key: 'A', text: '8×8' },
      { key: 'B', text: '5×5' },
      { key: 'C', text: '4×4' },
      { key: 'D', text: '3×3' },
    ],
    answer: 'C',
    keywords: ['4×4', '4x4'],
    explanation: 'Rumus: (8 - 5) + 1 = 4. Feature map = 4×4.',
    explanationSteps: ['(input - kernel) + 1', '(8 - 5) + 1 = 4', 'Feature map = 4×4'],
  },
  {
    id: 'conv-019',
    category: 'convolution',
    difficulty: 'medium',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[3,1,4],[1,5,9],[2,6,5]],
      kernel: [[1,0,0],[0,1,0],[0,0,1]],
    },
    answer: 13,
    explanation: 'Kernel identitas diagonal: mengambil elemen [0][0], [1][1], [2][2] dari input.',
    explanationSteps: ['3 + 5 + 5 = 13'],
  },
  {
    id: 'conv-020',
    category: 'convolution',
    difficulty: 'hard',
    type: 'numeric',
    question: 'Hitung hasil convolution dari input dan kernel berikut:',
    displayData: {
      input: [[6,2,4],[3,5,1],[7,4,2]],
      kernel: [[0,1,0],[1,0,1],[0,1,0]],
    },
    answer: 15,
    explanation: 'Kernel "plus" hanya mengambil 4 elemen (atas, kiri, kanan, bawah).',
    explanationSteps: [
      'Elemen kernel=1: atas=2, kiri=3, kanan=1, bawah=4',
      '2+3+1+4 = 10',
    ],
  },

  // ===== FEATURE MAP — 5 SOAL =====

  {
    id: 'fm-001',
    category: 'feature_map',
    difficulty: 'easy',
    type: 'numeric',
    question: 'Input gambar berukuran 5×5, kernel berukuran 3×3, tanpa padding, stride 1. Berapa ukuran dimensi output (feature map)?',
    answer: 3,
    explanation: 'Gunakan rumus: (input - kernel) + 1',
    explanationSteps: ['(5 - 3) + 1 = 3', 'Feature map = 3×3'],
  },
  {
    id: 'fm-002',
    category: 'feature_map',
    difficulty: 'easy',
    type: 'numeric',
    question: 'Input gambar berukuran 7×7, kernel berukuran 3×3, tanpa padding, stride 1. Berapa dimensi output?',
    answer: 5,
    explanation: 'Rumus: (input - kernel) + 1 = (7 - 3) + 1 = 5.',
    explanationSteps: ['(7 - 3) + 1 = 5', 'Feature map = 5×5'],
  },
  {
    id: 'fm-003',
    category: 'feature_map',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Input 9×9, kernel 4×4, tanpa padding, stride 1. Berapa ukuran feature map?',
    options: [
      { key: 'A', text: '9×9' },
      { key: 'B', text: '6×6' },
      { key: 'C', text: '5×5' },
      { key: 'D', text: '4×4' },
    ],
    answer: 'B',
    keywords: ['6×6', '6x6'],
    explanation: '(9 - 4) + 1 = 6. Feature map = 6×6.',
    explanationSteps: ['(9 - 4) + 1 = 6'],
  },
  {
    id: 'fm-004',
    category: 'feature_map',
    difficulty: 'hard',
    type: 'numeric',
    question: 'Jika input berukuran 10×10 dan kernel berukuran 4×4 (tanpa padding, stride 1), berapa jumlah total elemen dalam feature map?',
    answer: 49,
    explanation: '(10-4)+1 = 7. Jadi 7×7 = 49 elemen.',
    explanationSteps: ['Dimensi = (10 - 4) + 1 = 7', 'Total elemen = 7 × 7 = 49'],
  },
  {
    id: 'fm-005',
    category: 'feature_map',
    difficulty: 'medium',
    type: 'short_answer',
    question: 'Tuliskan rumus untuk menghitung ukuran output (feature map) dari operasi convolution tanpa padding dengan stride 1.',
    answer: '(input size - kernel size) + 1',
    keywords: ['input', 'kernel', '+1', 'minus', 'dikurang'],
    explanation: 'Rumus standar: Output size = (Input size - Kernel size) + 1. Ini berlaku untuk setiap dimensi (baris dan kolom).',
    explanationSteps: ['Output = (Input - Kernel) + 1'],
  },

  // ===== ReLU — 10 SOAL =====

  {
    id: 'relu-001',
    category: 'relu',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa fungsi ReLU dalam CNN?',
    options: [
      { key: 'A', text: 'Mengubah semua nilai negatif menjadi nilai positif acak' },
      { key: 'B', text: 'Mengganti semua nilai negatif dengan nol, mempertahankan nilai positif' },
      { key: 'C', text: 'Membagi semua nilai dengan nilai maksimum dalam matriks' },
      { key: 'D', text: 'Menormalkan distribusi nilai agar jumlahnya = 1' },
    ],
    answer: 'B',
    keywords: ['negatif', 'nol', 'positif dipertahankan'],
    explanation: 'ReLU (Rectified Linear Unit): f(x) = max(0, x). Semua nilai negatif menjadi 0, nilai positif tidak berubah. Ini menambahkan non-linearitas pada jaringan.',
    explanationSteps: ['ReLU(x) = max(0, x)', 'Jika x < 0 → 0', 'Jika x ≥ 0 → x'],
  },
  {
    id: 'relu-002',
    category: 'relu',
    difficulty: 'easy',
    type: 'matrix',
    question: 'Terapkan fungsi ReLU pada feature map berikut. Isi matriks output 3×3:',
    displayData: {
      feature_map: [[-3,5,-1],[7,-2,4],[0,-6,8]],
    },
    answer: [[0,5,0],[7,0,4],[0,0,8]],
    explanation: 'ReLU mengganti semua nilai negatif dengan 0. Nilai ≥ 0 tetap.',
    explanationSteps: [
      '-3 → 0, 5 → 5, -1 → 0',
      '7 → 7, -2 → 0, 4 → 4',
      '0 → 0, -6 → 0, 8 → 8',
    ],
  },
  {
    id: 'relu-003',
    category: 'relu',
    difficulty: 'medium',
    type: 'matrix',
    question: 'Terapkan ReLU pada feature map berikut:',
    displayData: {
      feature_map: [[4,-2,0],[-5,3,-1],[2,-3,6]],
    },
    answer: [[4,0,0],[0,3,0],[2,0,6]],
    explanation: 'Setiap nilai diproses dengan max(0, x).',
    explanationSteps: ['4→4, -2→0, 0→0', '-5→0, 3→3, -1→0', '2→2, -3→0, 6→6'],
  },
  {
    id: 'relu-004',
    category: 'relu',
    difficulty: 'easy',
    type: 'numeric',
    question: 'Berapa nilai ReLU dari -7?',
    answer: 0,
    explanation: 'ReLU(-7) = max(0, -7) = 0. Nilai negatif selalu menjadi 0.',
    explanationSteps: ['ReLU(-7) = max(0, -7) = 0'],
  },
  {
    id: 'relu-005',
    category: 'relu',
    difficulty: 'easy',
    type: 'numeric',
    question: 'Berapa nilai ReLU dari 12?',
    answer: 12,
    explanation: 'ReLU(12) = max(0, 12) = 12. Nilai positif tidak berubah.',
    explanationSteps: ['ReLU(12) = max(0, 12) = 12'],
  },
  {
    id: 'relu-006',
    category: 'relu',
    difficulty: 'medium',
    type: 'matrix',
    question: 'Terapkan ReLU pada feature map berikut:',
    displayData: {
      feature_map: [[-1,-4,2],[3,-7,0],[5,-2,-9]],
    },
    answer: [[0,0,2],[3,0,0],[5,0,0]],
    explanation: 'Terapkan max(0, x) pada setiap elemen.',
    explanationSteps: ['-1→0, -4→0, 2→2', '3→3, -7→0, 0→0', '5→5, -2→0, -9→0'],
  },
  {
    id: 'relu-007',
    category: 'relu',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Mengapa ReLU digunakan setelah convolution, bukan fungsi linear?',
    options: [
      { key: 'A', text: 'Karena fungsi linear lebih lambat dihitung' },
      { key: 'B', text: 'Karena kombinasi fungsi linear hanya menghasilkan fungsi linear lain — ReLU menambahkan non-linearitas sehingga jaringan dapat mempelajari pola kompleks' },
      { key: 'C', text: 'Karena ReLU memperbesar ukuran feature map' },
      { key: 'D', text: 'Karena ReLU mengurangi jumlah parameter' },
    ],
    answer: 'B',
    keywords: ['non-linear', 'nonlinear', 'pola kompleks'],
    explanation: 'Tanpa aktivasi non-linear, tumpukan layer convolution hanya setara dengan satu transformasi linear. ReLU memperkenalkan non-linearitas yang memungkinkan jaringan mempelajari representasi kompleks.',
  },
  {
    id: 'relu-008',
    category: 'relu',
    difficulty: 'hard',
    type: 'matrix',
    question: 'Setelah convolution menghasilkan feature map berikut, terapkan ReLU:',
    displayData: {
      feature_map: [[10,-3,5,-8],[2,-6,4,1],[-9,7,-2,3]],
    },
    answer: [[10,0,5,0],[2,0,4,1],[0,7,0,3]],
    explanation: 'Terapkan max(0, x) pada setiap elemen feature map 3×4.',
    explanationSteps: [
      'Baris 1: 10→10, -3→0, 5→5, -8→0',
      'Baris 2: 2→2, -6→0, 4→4, 1→1',
      'Baris 3: -9→0, 7→7, -2→0, 3→3',
    ],
  },
  {
    id: 'relu-009',
    category: 'relu',
    difficulty: 'easy',
    type: 'numeric',
    question: 'Berapa nilai ReLU dari 0?',
    answer: 0,
    explanation: 'ReLU(0) = max(0, 0) = 0.',
    explanationSteps: ['ReLU(0) = max(0, 0) = 0'],
  },
  {
    id: 'relu-010',
    category: 'relu',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Mengapa nilai 0 dalam ReLU disebut "dying ReLU problem"? Jelaskan secara singkat.',
    answer: 'neuron yang menghasilkan nilai negatif selalu menghasilkan 0, tidak berkontribusi pada training',
    keywords: ['neuron', 'negatif', 'mati', 'tidak update', 'gradient nol', 'dying'],
    explanation: 'Dying ReLU terjadi ketika neuron selalu menghasilkan nilai negatif sehingga ReLU selalu mengeluarkan 0. Gradientnya juga 0, sehingga bobot tidak pernah diupdate selama backpropagation — neuron "mati".',
  },

  // ===== POOLING — 10 SOAL =====

  {
    id: 'pool-001',
    category: 'pooling',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa tujuan utama operasi pooling dalam CNN?',
    options: [
      { key: 'A', text: 'Menambah detail pada gambar' },
      { key: 'B', text: 'Memperbesar ukuran feature map' },
      { key: 'C', text: 'Mereduksi ukuran spasial feature map (dimensionality reduction) sambil mempertahankan fitur penting' },
      { key: 'D', text: 'Mengubah gambar menjadi hitam putih' },
    ],
    answer: 'C',
    keywords: ['reduksi', 'ukuran', 'spasial', 'dimensionality'],
    explanation: 'Pooling mereduksi dimensi spasial feature map sehingga jumlah parameter dan komputasi berkurang, sekaligus membuat representasi lebih robust terhadap pergeseran kecil.',
  },
  {
    id: 'pool-002',
    category: 'pooling',
    difficulty: 'medium',
    type: 'matrix',
    question: 'Lakukan Max Pooling 2×2 (tanpa overlap) pada matriks berikut:',
    displayData: {
      feature_map: [[5,2,8,1],[4,7,3,6],[9,2,5,4],[1,8,6,3]],
      pooling_window: 2,
    },
    answer: [[7,8],[9,6]],
    explanation: 'Bagi matriks menjadi 4 blok 2×2, ambil nilai maksimum dari setiap blok.',
    explanationSteps: [
      'Blok kiri atas [5,2,4,7] → max = 7',
      'Blok kanan atas [8,1,3,6] → max = 8',
      'Blok kiri bawah [9,2,1,8] → max = 9',
      'Blok kanan bawah [5,4,6,3] → max = 6',
      'Output: [[7,8],[9,6]]',
    ],
  },
  {
    id: 'pool-003',
    category: 'pooling',
    difficulty: 'medium',
    type: 'matrix',
    question: 'Lakukan Mean Pooling 2×2 (tanpa overlap) pada matriks berikut:',
    displayData: {
      feature_map: [[5,2,8,1],[4,7,3,6],[9,2,5,4],[1,8,6,3]],
      pooling_window: 2,
    },
    answer: [[4.5,4.5],[5,4.5]],
    explanation: 'Bagi matriks menjadi blok 2×2, hitung rata-rata setiap blok.',
    explanationSteps: [
      'Blok kiri atas (5+2+4+7)/4 = 18/4 = 4.5',
      'Blok kanan atas (8+1+3+6)/4 = 18/4 = 4.5',
      'Blok kiri bawah (9+2+1+8)/4 = 20/4 = 5.0',
      'Blok kanan bawah (5+4+6+3)/4 = 18/4 = 4.5',
    ],
  },
  {
    id: 'pool-004',
    category: 'pooling',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa perbedaan utama antara Max Pooling dan Mean Pooling?',
    options: [
      { key: 'A', text: 'Max Pooling lebih lambat dari Mean Pooling' },
      { key: 'B', text: 'Max Pooling mengambil nilai tertinggi dari window, sedangkan Mean Pooling mengambil rata-rata nilai dalam window' },
      { key: 'C', text: 'Max Pooling menghasilkan output yang lebih besar dari Mean Pooling' },
      { key: 'D', text: 'Max Pooling hanya digunakan di layer pertama CNN' },
    ],
    answer: 'B',
    keywords: ['maksimum', 'rata-rata', 'mean', 'max'],
    explanation: 'Max Pooling: pilih nilai tertinggi dalam window. Mean Pooling: hitung rata-rata semua nilai dalam window. Max Pooling lebih umum digunakan karena lebih baik dalam mempertahankan fitur dominan.',
  },
  {
    id: 'pool-005',
    category: 'pooling',
    difficulty: 'medium',
    type: 'matrix',
    question: 'Lakukan Max Pooling 2×2 (tanpa overlap) pada matriks berikut:',
    displayData: {
      feature_map: [[3,1,4,2],[5,9,6,8],[2,7,1,3],[4,6,5,2]],
      pooling_window: 2,
    },
    answer: [[9,8],[7,5]],
    explanation: 'Ambil nilai terbesar dari setiap blok 2×2.',
    explanationSteps: [
      'Blok kiri atas [3,1,5,9] → max = 9',
      'Blok kanan atas [4,2,6,8] → max = 8',
      'Blok kiri bawah [2,7,4,6] → max = 7',
      'Blok kanan bawah [1,3,5,2] → max = 5',
    ],
  },
  {
    id: 'pool-006',
    category: 'pooling',
    difficulty: 'hard',
    type: 'matrix',
    question: 'Lakukan Mean Pooling 2×2 (tanpa overlap) pada matriks berikut:',
    displayData: {
      feature_map: [[4,8,2,6],[2,0,4,2],[6,4,8,0],[2,6,4,4]],
      pooling_window: 2,
    },
    answer: [[3.5,3.5],[4.5,4]],
    explanation: 'Hitung rata-rata setiap blok 2×2.',
    explanationSteps: [
      'Blok kiri atas (4+8+2+0)/4 = 14/4 = 3.5',
      'Blok kanan atas (2+6+4+2)/4 = 14/4 = 3.5',
      'Blok kiri bawah (6+4+2+6)/4 = 18/4 = 4.5',
      'Blok kanan bawah (8+0+4+4)/4 = 16/4 = 4.0',
    ],
  },
  {
    id: 'pool-007',
    category: 'pooling',
    difficulty: 'easy',
    type: 'numeric',
    question: 'Input feature map berukuran 4×4. Setelah Max Pooling 2×2 tanpa overlap, berapa ukuran output?',
    answer: 2,
    explanation: '4 / 2 = 2. Output berukuran 2×2.',
    explanationSteps: ['Dimensi input 4', 'Window 2×2', 'Output = 4 / 2 = 2', 'Output size = 2×2'],
  },
  {
    id: 'pool-008',
    category: 'pooling',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Jelaskan mengapa Max Pooling lebih sering digunakan dibanding Mean Pooling dalam CNN untuk klasifikasi gambar.',
    answer: 'max pooling mempertahankan fitur paling dominan dan lebih robust terhadap noise',
    keywords: ['dominan', 'fitur kuat', 'robust', 'noise', 'paling aktif'],
    explanation: 'Max Pooling memilih nilai terbesar yang mewakili aktivasi paling kuat dalam window. Fitur yang kuat (seperti tepi atau sudut) lebih penting untuk klasifikasi daripada rata-rata. Mean Pooling merata-ratakan sinyal sehingga bisa "melemahkan" fitur dominan.',
  },
  {
    id: 'pool-009',
    category: 'pooling',
    difficulty: 'medium',
    type: 'matrix',
    question: 'Lakukan Max Pooling 2×2 (tanpa overlap) pada matriks berikut:',
    displayData: {
      feature_map: [[0,2,1,4],[3,5,6,2],[7,1,3,8],[4,9,5,1]],
      pooling_window: 2,
    },
    answer: [[5,6],[9,8]],
    explanation: 'Ambil nilai max dari setiap blok 2×2.',
    explanationSteps: [
      'Blok kiri atas [0,2,3,5] → 5',
      'Blok kanan atas [1,4,6,2] → 6',
      'Blok kiri bawah [7,1,4,9] → 9',
      'Blok kanan bawah [3,8,5,1] → 8',
    ],
  },
  {
    id: 'pool-010',
    category: 'pooling',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Feature map 6×6 diproses dengan Max Pooling 2×2 tanpa overlap. Berapa ukuran output?',
    options: [
      { key: 'A', text: '6×6' },
      { key: 'B', text: '4×4' },
      { key: 'C', text: '3×3' },
      { key: 'D', text: '2×2' },
    ],
    answer: 'C',
    keywords: ['3×3', '3x3'],
    explanation: '6 / 2 = 3. Dengan window 2×2 tanpa overlap, output = 3×3.',
    explanationSteps: ['Dimensi output = input_size / window_size', '6 / 2 = 3', 'Output = 3×3'],
  },

  // ===== HIERARCHICAL FEATURES — 5 SOAL =====

  {
    id: 'hier-001',
    category: 'hierarchical',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Fitur apa yang umumnya dipelajari oleh layer convolution paling awal dalam CNN?',
    options: [
      { key: 'A', text: 'Wajah dan objek kompleks secara utuh' },
      { key: 'B', text: 'Tepi (edge), garis, dan sudut' },
      { key: 'C', text: 'Probabilitas kelas output' },
      { key: 'D', text: 'Tekstur seluruh objek' },
    ],
    answer: 'B',
    keywords: ['edge', 'tepi', 'garis', 'sudut', 'corner'],
    explanation: 'Layer awal CNN mendeteksi fitur low-level seperti tepi (edge), garis, dan sudut. Semakin dalam layer, semakin abstrak fitur yang dideteksi.',
  },
  {
    id: 'hier-002',
    category: 'hierarchical',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Urutan yang benar dari fitur yang dipelajari CNN dari layer awal ke layer akhir adalah?',
    options: [
      { key: 'A', text: 'Wajah → Tekstur → Tepi' },
      { key: 'B', text: 'Tepi/Sudut → Tekstur/Pola → Bagian Objek (mata, roda)' },
      { key: 'C', text: 'Piksel → Probabilitas → Kelas' },
      { key: 'D', text: 'Kernel → Feature Map → Pooling' },
    ],
    answer: 'B',
    keywords: ['tepi', 'tekstur', 'pola', 'objek', 'mata', 'roda'],
    explanation: 'Hierarchical features: Layer awal → tepi/garis/sudut (low-level). Layer tengah → tekstur, pola lokal. Layer akhir → bagian objek kompleks seperti mata, roda, atau wajah utuh (high-level).',
  },
  {
    id: 'hier-003',
    category: 'hierarchical',
    difficulty: 'medium',
    type: 'short_answer',
    question: 'Jelaskan konsep hierarchical features dalam CNN. Apa yang dimaksud dengan hirarki fitur dari layer rendah ke layer tinggi?',
    answer: 'layer awal belajar fitur sederhana seperti tepi dan garis, layer tengah belajar tekstur, layer akhir belajar fitur kompleks seperti objek',
    keywords: ['sederhana', 'tepi', 'kompleks', 'hirarki', 'layer', 'abstrak'],
    explanation: 'Hierarchical features: CNN belajar fitur secara hierarkis. Layer awal → fitur sederhana (tepi, garis, sudut). Layer tengah → kombinasi fitur sederhana menjadi tekstur dan pola. Layer akhir → kombinasi pola menjadi bagian objek atau objek utuh.',
  },
  {
    id: 'hier-004',
    category: 'hierarchical',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Fitur apa yang biasanya dideteksi di layer tengah CNN (intermediate layer)?',
    options: [
      { key: 'A', text: 'Piksel mentah dari input asli' },
      { key: 'B', text: 'Tepi dan garis lurus saja' },
      { key: 'C', text: 'Tekstur, pola berulang, dan kombinasi tepi lokal' },
      { key: 'D', text: 'Probabilitas akhir kelas output' },
    ],
    answer: 'C',
    keywords: ['tekstur', 'pola', 'berulang', 'kombinasi'],
    explanation: 'Layer tengah mengkombinasikan fitur sederhana dari layer awal untuk mendeteksi tekstur (garis berulang, gradien), pola lokal, dan bentuk dasar.',
  },
  {
    id: 'hier-005',
    category: 'hierarchical',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Mengapa kemampuan CNN untuk belajar hierarchical features membuatnya unggul dibanding metode klasifikasi gambar sederhana?',
    answer: 'CNN dapat secara otomatis mengekstrak fitur relevan dari data, tidak perlu feature engineering manual',
    keywords: ['otomatis', 'ekstrak', 'tanpa manual', 'feature engineering', 'representasi'],
    explanation: 'CNN secara otomatis mempelajari representasi fitur yang relevan langsung dari data. Metode konvensional membutuhkan feature engineering manual (seperti HOG, SIFT) yang butuh keahlian domain. CNN menghilangkan kebutuhan ini dengan mempelajari hierarki fitur dari data sendiri.',
  },

  // ===== SOFTMAX — 5 SOAL =====

  {
    id: 'soft-001',
    category: 'softmax',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa fungsi Softmax dalam output layer CNN?',
    options: [
      { key: 'A', text: 'Mengubah nilai negatif menjadi nol' },
      { key: 'B', text: 'Mengkonversi vektor skor menjadi distribusi probabilitas (jumlah = 1)' },
      { key: 'C', text: 'Memilih nilai terbesar dari feature map' },
      { key: 'D', text: 'Mengurangi ukuran feature map setengahnya' },
    ],
    answer: 'B',
    keywords: ['probabilitas', 'distribusi', 'jumlah 1', 'sum 1'],
    explanation: 'Softmax mengkonversi raw scores (logits) menjadi distribusi probabilitas. Setiap nilai output antara 0 dan 1, dan semua nilai dijumlahkan menjadi 1.',
    explanationSteps: ['softmax(z_i) = e^(z_i) / Σe^(z_j)', 'Output: nilai antara 0-1', 'Total semua output = 1'],
  },
  {
    id: 'soft-002',
    category: 'softmax',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Dalam Softmax, rumus softmax(z_i) = e^(z_i) / Σe^(z_j). Apa yang disebut "denominator" (pembagi)?',
    options: [
      { key: 'A', text: 'e^(z_i) — nilai eksponensial kelas i' },
      { key: 'B', text: 'Σe^(z_j) — jumlah semua nilai eksponensial' },
      { key: 'C', text: 'z_i — raw score kelas i' },
      { key: 'D', text: 'z_j — raw score semua kelas' },
    ],
    answer: 'B',
    keywords: ['jumlah', 'semua', 'eksponensial', 'sigma'],
    explanation: 'Denominator adalah Σe^(z_j) — jumlah nilai eksponensial dari SEMUA kelas. Ini memastikan output terdistribusi sebagai probabilitas yang jumlahnya 1.',
  },
  {
    id: 'soft-003',
    category: 'softmax',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Jika terdapat 3 kelas dan Softmax menghasilkan [0.7, 0.2, 0.1], kelas mana yang diprediksi?',
    options: [
      { key: 'A', text: 'Kelas 2 (nilai 0.2)' },
      { key: 'B', text: 'Kelas 3 (nilai 0.1)' },
      { key: 'C', text: 'Kelas 1 (nilai 0.7)' },
      { key: 'D', text: 'Tidak dapat ditentukan' },
    ],
    answer: 'C',
    keywords: ['kelas 1', 'nilai tertinggi', '0.7', 'probabilitas tertinggi'],
    explanation: 'Model memprediksi kelas dengan probabilitas tertinggi. Kelas 1 memiliki probabilitas 0.7 (70%), tertinggi dari ketiga kelas.',
  },
  {
    id: 'soft-004',
    category: 'softmax',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Berapa total jumlah output Softmax untuk 5 kelas?',
    options: [
      { key: 'A', text: '5' },
      { key: 'B', text: 'Tidak tentu' },
      { key: 'C', text: '1' },
      { key: 'D', text: '0' },
    ],
    answer: 'C',
    keywords: ['1', 'satu', 'total sama dengan 1'],
    explanation: 'Output Softmax selalu berjumlah 1 (satu) karena merupakan distribusi probabilitas. Tidak peduli berapa banyak kelas, total output = 1.',
  },
  {
    id: 'soft-005',
    category: 'softmax',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Jelaskan mengapa Softmax menggunakan fungsi eksponensial (e^x) daripada hanya normalisasi linear biasa.',
    answer: 'eksponensial memperbesar perbedaan antar kelas sehingga kelas terkuat terlihat lebih jelas, dan selalu menghasilkan nilai positif',
    keywords: ['memperbesar', 'perbedaan', 'positif', 'eksponensial', 'kontras'],
    explanation: 'Fungsi eksponensial: (1) Memastikan semua nilai positif (e^x selalu > 0). (2) Memperbesar perbedaan antar nilai — kelas dengan skor lebih tinggi mendapat probabilitas yang lebih dominan. Normalisasi linear bisa menghasilkan nilai negatif jika ada skor negatif.',
  },

  // ===== ARCHITECTURE — 5 SOAL =====

  {
    id: 'arch-001',
    category: 'architecture',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Urutan yang benar dari alur CNN untuk klasifikasi gambar adalah?',
    options: [
      { key: 'A', text: 'Input → Flatten → Convolution → Pooling → ReLU → Softmax' },
      { key: 'B', text: 'Input → Convolution → ReLU → Pooling → Flatten → Fully Connected → Softmax' },
      { key: 'C', text: 'Input → Softmax → Convolution → Pooling → Output' },
      { key: 'D', text: 'Input → Pooling → Convolution → Flatten → Output' },
    ],
    answer: 'B',
    keywords: ['convolution', 'relu', 'pooling', 'flatten', 'softmax'],
    explanation: 'Alur standar CNN: Input → Convolution (ekstraksi fitur) → ReLU (non-linearitas) → Pooling (reduksi dimensi) → [bisa diulang] → Flatten (1D) → Fully Connected → Softmax (probabilitas kelas).',
  },
  {
    id: 'arch-002',
    category: 'architecture',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Apa fungsi operasi Flatten dalam CNN?',
    options: [
      { key: 'A', text: 'Mengecilkan gambar menjadi setengah ukurannya' },
      { key: 'B', text: 'Mengubah feature map multi-dimensi menjadi vektor satu dimensi untuk dimasukkan ke fully connected layer' },
      { key: 'C', text: 'Menambah kedalaman feature map' },
      { key: 'D', text: 'Mengacak urutan piksel dalam gambar' },
    ],
    answer: 'B',
    keywords: ['satu dimensi', 'vektor', 'fully connected', '1D'],
    explanation: 'Flatten mengubah feature map berukuran H×W×C menjadi vektor 1D dengan panjang H×W×C. Ini diperlukan karena fully connected layer membutuhkan input berupa vektor 1D.',
    explanationSteps: ['Feature map: 7×7×64', 'Setelah flatten: 3136 nilai', 'Dimasukkan ke fully connected layer'],
  },
  {
    id: 'arch-003',
    category: 'architecture',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Jelaskan secara lengkap alur data dari gambar input hingga output prediksi kelas dalam CNN. Sebutkan setiap tahap utama.',
    answer: 'input gambar, convolution mengekstrak fitur, relu menambah nonlinearitas, pooling mereduksi dimensi, flatten mengubah ke 1D, fully connected mengklasifikasi, softmax menghasilkan probabilitas',
    keywords: ['convolution', 'relu', 'pooling', 'flatten', 'softmax', 'fully connected', 'fitur'],
    explanation: 'Alur lengkap: 1) Input: gambar matriks piksel. 2) Convolution: kernel mengekstrak feature map. 3) ReLU: aktivasi non-linear. 4) Pooling: reduksi dimensi spasial. 5) [Layer 2...N berulang]. 6) Flatten: ubah ke vektor 1D. 7) Fully Connected: kombinasi fitur. 8) Softmax: distribusi probabilitas. 9) Output: kelas dengan probabilitas tertinggi.',
  },
  {
    id: 'arch-004',
    category: 'architecture',
    difficulty: 'medium',
    type: 'multiple_choice',
    question: 'Mengapa gambar tidak langsung dimasukkan seluruh pikselnya ke neural network biasa (bukan CNN)?',
    options: [
      { key: 'A', text: 'Karena neural network biasa tidak bisa memproses angka' },
      { key: 'B', text: 'Karena gambar berukuran besar akan menghasilkan sangat banyak parameter jika setiap piksel terhubung ke setiap neuron (parameter explosion)' },
      { key: 'C', text: 'Karena gambar harus diubah ke format audio terlebih dahulu' },
      { key: 'D', text: 'Karena neural network hanya memproses 1 dimensi' },
    ],
    answer: 'B',
    keywords: ['parameter', 'besar', 'komputasi', 'setiap piksel'],
    explanation: 'Gambar 224×224×3 = 150.528 piksel. Jika dihubungkan ke hidden layer 512 neuron: 77 juta parameter hanya dari satu layer. CNN menggunakan parameter sharing melalui kernel yang jauh lebih efisien.',
  },
  {
    id: 'arch-005',
    category: 'architecture',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Setelah serangkaian Convolution → ReLU → Pooling, apa langkah yang dilakukan sebelum memasukkan data ke Fully Connected layer?',
    options: [
      { key: 'A', text: 'Convolution lagi dengan kernel lebih besar' },
      { key: 'B', text: 'Softmax untuk mendapatkan probabilitas awal' },
      { key: 'C', text: 'Flatten — mengubah feature map multi-dimensi menjadi vektor 1D' },
      { key: 'D', text: 'Mean Pooling dengan window maksimum' },
    ],
    answer: 'C',
    keywords: ['flatten', '1D', 'vektor'],
    explanation: 'Sebelum masuk ke Fully Connected layer, feature map harus di-flatten menjadi vektor 1D. Fully Connected layer membutuhkan input berupa vektor, bukan matriks 2D/3D.',
  },

  // ===== COMBINED / GABUNGAN — 5 SOAL =====

  {
    id: 'comb-001',
    category: 'convolution',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Sebuah feature map hasil convolution adalah:\n[[-3, 5], [7, -2]]\n\nSetelah ReLU diterapkan, lalu Max Pooling 2×2, hasilnya adalah?',
    options: [
      { key: 'A', text: '7' },
      { key: 'B', text: '5' },
      { key: 'C', text: '7' },
      { key: 'D', text: '0' },
    ],
    answer: 'C',
    keywords: ['7'],
    explanation: 'Step 1 - ReLU: [[-3,5],[7,-2]] → [[0,5],[7,0]]. Step 2 - Max Pooling 2×2: max(0,5,7,0) = 7.',
    explanationSteps: [
      'Feature map: [[-3,5],[7,-2]]',
      'Setelah ReLU: [[0,5],[7,0]]',
      'Max Pooling 2×2: max(0,5,7,0) = 7',
    ],
  },
  {
    id: 'comb-002',
    category: 'relu',
    difficulty: 'hard',
    type: 'numeric',
    question: 'Convolution menghasilkan nilai -15. Setelah ReLU diterapkan, lalu nilai tersebut adalah satu-satunya dalam window 1×1 pooling. Berapa output akhir?',
    answer: 0,
    explanation: 'ReLU(-15) = 0. Max pooling dari satu nilai 0 = 0.',
    explanationSteps: ['Convolution = -15', 'ReLU(-15) = 0', 'Max Pooling(0) = 0'],
  },
  {
    id: 'comb-003',
    category: 'architecture',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Sebuah gambar input berukuran 5×5 diproses dengan: kernel 3×3 → ReLU → Max Pooling 2×2. Jelaskan ukuran output di setiap tahap.',
    answer: 'setelah convolution 3x3, ukuran menjadi 3x3, setelah pooling 2x2 menjadi 1x1',
    keywords: ['3×3', '3x3', '1×1', '1x1', 'convolution', 'pooling'],
    explanation: 'Tahap 1 - Convolution: (5-3)+1 = 3. Feature map = 3×3. Tahap 2 - ReLU: ukuran tetap 3×3. Tahap 3 - Max Pooling 2×2: 3/2 = 1 (floor). Output = 1×1 (satu nilai).',
    explanationSteps: [
      'Input: 5×5',
      'Convolution 3×3: (5-3)+1 = 3 → Feature map 3×3',
      'ReLU: ukuran tetap 3×3',
      'Max Pooling 2×2: 3/2 ≈ 1 → Output 1×1',
    ],
  },
  {
    id: 'comb-004',
    category: 'architecture',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Jika sebuah input 4×4 dikenai convolution 3×3 menghasilkan feature map 2×2, kemudian Max Pooling 2×2 diterapkan, apa ukuran akhir output?',
    options: [
      { key: 'A', text: '2×2' },
      { key: 'B', text: '1×1' },
      { key: 'C', text: '4×4' },
      { key: 'D', text: '3×3' },
    ],
    answer: 'B',
    keywords: ['1×1', '1x1'],
    explanation: 'Convolution 3×3 pada input 4×4: (4-3)+1 = 2 → Feature map 2×2. Max Pooling 2×2 pada 2×2: 2/2 = 1 → Output 1×1.',
    explanationSteps: [
      'Input 4×4 + Kernel 3×3 → (4-3)+1=2 → Feature map 2×2',
      'Max Pooling 2×2 pada 2×2 → 1×1',
    ],
  },
  {
    id: 'comb-005',
    category: 'architecture',
    difficulty: 'hard',
    type: 'short_answer',
    question: 'Setelah seluruh tahap CNN (convolution, relu, pooling, flatten), kita mendapatkan vektor fitur. Jelaskan apa yang terjadi selanjutnya hingga menghasilkan prediksi kelas.',
    answer: 'vektor dimasukkan ke fully connected layer, diproses, lalu softmax menghasilkan distribusi probabilitas, kelas dengan probabilitas tertinggi adalah prediksi',
    keywords: ['fully connected', 'softmax', 'probabilitas', 'kelas tertinggi', 'prediksi'],
    explanation: 'Setelah flatten: (1) Vektor 1D dimasukkan ke Fully Connected layer → kombinasi linier semua fitur. (2) Softmax di output layer → mengkonversi ke probabilitas (jumlah=1). (3) Argmax → kelas dengan probabilitas tertinggi dipilih sebagai prediksi akhir.',
    explanationSteps: [
      'Flatten → vektor 1D',
      'Fully Connected → representasi tingkat tinggi',
      'Softmax → distribusi probabilitas',
      'Argmax → prediksi kelas',
    ],
  },
];

export function getQuestions(config: { count: number; category: string; difficulty: string; wrongIds?: string[] }): Question[] {
  let pool = [...QUESTION_BANK];

  // Filter category
  if (config.category !== 'all') {
    if (config.category === 'wrong' && config.wrongIds && config.wrongIds.length > 0) {
      pool = pool.filter(q => config.wrongIds!.includes(q.id));
    } else if (config.category !== 'wrong') {
      pool = pool.filter(q => q.category === config.category);
    }
  }

  // Filter difficulty
  if (config.difficulty !== 'mixed') {
    pool = pool.filter(q => q.difficulty === config.difficulty);
  }

  // Prioritize hard questions if difficulty is hard
  if (config.difficulty === 'hard') {
    pool = pool.sort((a, b) => {
      if (a.difficulty === 'hard' && b.difficulty !== 'hard') return -1;
      if (b.difficulty === 'hard' && a.difficulty !== 'hard') return 1;
      return 0;
    });
  }

  // Shuffle
  pool = pool.sort(() => Math.random() - 0.5);

  // Return up to count
  return pool.slice(0, config.count);
}
